"use client"
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/AuthProvider";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar";
import { CustomThemeProvider } from "./ThemeProvider";
import { ThemeProvider } from "next-themes";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
import { Toaster } from "@/components/ui/sonner"
import { usePathname } from "next/navigation";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const pathname = usePathname();
  const authPages = ["/sign-up", "/sign-in", "/verify"];

  const isAuthPage = authPages.includes(pathname);
  return (
      <AuthProvider>
    <html lang="en" suppressHydrationWarning>

        {/* <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}> */}
        <body className={""}>
        <CustomThemeProvider>
          {!isAuthPage ? (
            <SidebarProvider>
              <AppSidebar />
              <main className="w-full">
                <SidebarTrigger />
                {children}
              </main>
            </SidebarProvider>
          ) : (
            <main>{children}</main>
          )}
    </CustomThemeProvider>
          <Toaster />
        </body>
    </html>
      </AuthProvider>
  );
}
